name: Cleanup gh-pages

description: 'Action to cleanup reports in gh-pages branch'

concurrency: cleanup_gh_pages

runs:
  using: 'composite'
  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Cleanup reports folder
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        cd reports

        if [ -d "$BRANCH_NAME" ]; then
          rm -rf -- $BRANCH_NAME
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git diff --quiet && git diff --staged --quiet || git commit -am "Deleting $BRANCH_NAME folder contents."
          git push origin
        else
          echo "$BRANCH_NAME directory does not exists."
        fi
