name: Publish gh-pages

description: 'Action to publish reports to gh-pages'

inputs:
  artifacts:
    description: 'Artifacts to be published to gh-pages'
    required: true
  comment-title:
    description: 'Comment title'
    required: false
    default: 'Test reports'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.artifacts }}" ]
        then
          echo "artifacts must be provided";
          exit 1;
        fi

        echo "${{ GITHUB_REF_NAME }}"
        echo "${{ GITHUB_REPOSITORY }}"
        echo "${{ GITHUB_REPOSITORY_OWNER }}"
        echo "${{ GITHUB_REPOSITORY_OWNER_ID }}"
        echo "${{ GITHUB_SERVER_URL }}"
        echo "${{ GITHUB_SHA }}"
        echo "${{ GITHUB_WORKSPACE }}"

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: reports
        path: artifacts/reports

    - name: Set the environment variables
      shell: bash
      run: |
        echo "branch_name=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        echo "sha_short=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Commit reports
      shell: bash
      run: |
        mkdir -p reports/${{ env.branch_name }}
        cd reports/${{ env.branch_name }}
        
        rm -rf -- *

        echo '${{ inputs.artifacts }}' | jq -r 'to_entries[] | "\(.value)"' | while read report_path; do
          cp -R ${{ github.workspace }}/artifacts/reports/$report_path .
        done
        
        rm -rf -- ${{ github.workspace }}/artifacts/
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add .
        git commit -am ${{ env.branch_name }} || true
        git push --force

    - name: Comment report details on pull request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          function generateComment() {
            let commentBody = "";
            const artifactsObj = JSON.parse(`${{ inputs.artifacts }}`);
            
            for (const key in artifactsObj) {
              commentBody += `- [${key}](${{ inputs.domain }}/reports/${{ env.branch_name }}/${artifactsObj[key]})\n`;
            }

            return `## ${{ inputs.comment-title }}\n\nCommit: ${{ env.sha_short }}\n\n${commentBody}`;
          }
          
          const githubActionBotUser = await github.rest.users.getByUsername({ username: 'github-actions[bot]' });
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number
          });
          const botComment = comments.find(comment => comment.user.id === githubActionBotUser.data.id && comment.body.includes(`## ${{ inputs.comment-title }}`));
          
          if(botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: `${generateComment()}\n\n:recycle: This comment has been updated with latest results.`
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: generateComment()
            });
          }
