name: Publish gh-pages

description: 'Action to publish reports to gh-pages'

concurrency: publish_gh_pages

inputs:
  artifacts:
    description: 'Artifacts to be published to gh-pages'
    required: true
  domain:
    description: 'GH pages domain name'
    required: true
  comment-title:
    description: 'Comment title'
    required: false
    default: 'Test reports'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.artifacts }}" ]
        then
          echo "artifacts must be provided";
          exit 1;
        fi

        [ "${{ inputs.domain }}" ] || { echo "gh-pages domain must be provided"; exit 1; }

    - name: Build artifacts to be published
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/artifacts

        echo '${{ inputs.artifacts }}' | jq -r 'to_entries[] | "\(.value)"' | while read report_path; do
          cp -R $report_path ${{ github.workspace }}/artifacts
        done

        ls -R ${{ github.workspace }}/artifacts

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        clean: false

    # - name: Download artifacts
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: reports
    #     path: artifacts/reports

    - name: Set the environment variables
      shell: bash
      run: |
        echo "branch_name=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        echo "sha_short=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

    - name: Commit reports
      shell: bash
      run: |
        mkdir -p reports/${{ env.branch_name }}
        cd reports/${{ env.branch_name }}
        
        rm -rf -- *

        ls -R ${{ github.workspace }}/artifacts/

        cp -R ${{ github.workspace }}/artifacts/ .

        # echo '${{ inputs.artifacts }}' | jq -r 'to_entries[] | "\(.value)"' | while read report_path; do
        #   cp -R ${{ github.workspace }}/artifacts/reports/$report_path .
        # done
        
        rm -rf -- ${{ github.workspace }}/artifacts/
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add .
        git commit -am ${{ env.BRANCH_NAME }} || true
        git push

    - name: Comment report details on pull request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number
          });
          
          const githubActionBotUser = await github.rest.users.getByUsername({ username: 'github-actions[bot]' });
          
          const botComment = comments.find(comment => comment.user.id === githubActionBotUser.data.id && comment.body.includes(`## ${{ inputs.comment-title }}`));
          
          const artifactsObj = JSON.parse(`${{ inputs.artifacts }}`);
          let commentBody = "";
          
          for (const key in artifactsObj) {
            commentBody += `- [${key}](${{ inputs.domain }}/reports/${{ env.branch_name }}/${artifactsObj[key]})\n`
          }

          const comment = `## ${{ inputs.comment-title }}\n\nCommit: ${{ env.sha_short }}\n\n${commentBody}`
          
          if(botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: `${comment}\n\n:recycle: This comment has been updated with latest results.`
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: comment
            });
          }
