name: Publish

description: 'Publish report to gh-pages'

inputs:
  comment-title:
    description: 'Pull request comment title'
    required: true
    type: string
  comment-body:
    description: 'Pull request comment body'
    required: true
    type: string
  artifact-name:
    description: 'Artifact to be published to gh-pages'
    required: true
    type: string
  publish-artifact-paths:
    description: 'Comma separated list of artifact paths to be published to gh-pages. If not specified, publishes all entire content from artifact directory.'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: artifacts

    - name: Set the branch name
      shell: bash
      run: |
        echo "branch_name=${{ github.head_ref || github.ref_name }}" >> "$GITHUB_ENV"
        echo ${{ github.head_ref || github.ref_name }}

    - name: Commit reports
      shell: bash
      run: |
        mkdir -p reports
        cd reports

        mkdir -p ${{ env.branch_name }}
        cd ${{ env.branch_name }}
        
        rm -rf *
        
        if [ -z "${{ inputs.publish-artifact-paths }}" ]
          cp -R ${{ github.workspace }}/artifacts/* .
        then
        else
          IFS=', ' read -r -a artifact_paths <<< "${{ inputs.publish-artifact-paths }}"
          for path in "${artifact_paths[@]}"
          do
            echo $path
            cp -R ${{ github.workspace }}/artifacts/$path/* .
            ls -R ${{ github.workspace }}/artifacts/$path
          done
        fi
        
        rm -R ${{ github.workspace }}/artifacts/
        
        git config user.name github-actions
        git config user.email github-actions@github.com
        git status
        git add .
        git commit -am ${{ env.branch_name }} || true
        git push

    - name: Comment report details on pull request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number
          });

          const botComment = comments.find(comment => comment.user.id === 41898282 && comment.body.includes(`## ${{ inputs.comment-title }}`));
          const comment = `## ${{ inputs.comment-title }}\n\n${{ inputs.comment-body }}`
          
          if(botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: `${comment}\n\n:recycle: This comment has been updated with latest results.`,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: comment,
            });
          }
