name: Reusable workflow - Cleanup gh-pages

on:
  workflow_call:

concurrency:
  group: gh-pages-${{ github.ref }}

jobs:
  cleanup-gh-pages:
    name: Cleanup gh-pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Cleanup reports folder
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          cd reports

          echo "${{ github.ref }}"

          if [ -d "$BRANCH_NAME" ]; then
            rm -rf -- $BRANCH_NAME
            git config user.name github-actions
            git config user.email github-actions@github.com

            git status
            git add .
            git commit --amend -am "Deleting $BRANCH_NAME directory." || true
            
            while !(git push --force-with-lease)
            do
              git reset --soft HEAD@{1}
              git stash
              git pull --rebase
              git stash pop
              git add .
              git commit --amend -am "Deleting $BRANCH_NAME directory." || true
            done
          else
            echo "$BRANCH_NAME directory does not exists."
          fi
