name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup_gh_pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Cleanup reports folder
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          cd reports
          cd $BRANCH_NAME
          
          rm -rf *
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git diff --quiet && git diff --staged --quiet || git commit -am "Deleting $BRANCH_NAME folder contents."
          git push origin
