name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup_gh_pages:
    name: Cleanup gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    uses: IndranilKhedkar/github-actions/.github/actions/cleanup-gh-pages.yml@test-github-workflow