name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup_gh_pages:
    name: Cleanup gh-pages
    permissions:
      contents: write
    uses: IndranilKhedkar/github-actions/.github/workflows/cleanup-reports-in-gh-pages.yml@test-github-workflow-1
