name: Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup_gh_pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Cleanup reports folder
        uses: IndranilKhedkar/github-actions/.github/actions/cleanup-gh-pages@test-github-actions