name: Run Tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  unit:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read
      checks: write
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Run unit tests
        run: |
          cd client
          npm run test:unit:ci:coverage

      - name: Upload unit test reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: client/reports
          retention-days: 1

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: client/test-results/junit-unit-test-result.xml
          report_individual_runs: true

      - name: Publish code coverage report
        uses: IndranilKhedkar/github-actions/.github/actions/publish-gh-pages@test-github-actions
        with:
          comment-title: 'Unit test reports'
          comment-body: |
            Code coverage report for commit [${{ github.event.pull_request.head.sha }}](https://indranilkhedkar.github.io/github-actions/reports/${{ github.head_ref || github.ref_name }}/unit-tests-coverage).
            Test results report for commit [${{ github.event.pull_request.head.sha }}](https://indranilkhedkar.github.io/github-actions/reports/${{ github.head_ref || github.ref_name }}/unit-tests).
          artifact-name: 'reports'
