name: Run Tests

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  unit:
    name: Unit Tests
    timeout-minutes: 10
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Run unit tests
        run: |
          cd client
          npm run test:unit:ci:coverage

      - name: Upload unit test reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: client/reports
          retention-days: 1

      - name: Publish unit test result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: client/reports/unit-tests-junit.xml
          report_individual_runs: true

      - name: Set output variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT
          echo $(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          echo "github.head_ref ${{ github.head_ref }}"
          echo "github.ref_name ${{ github.ref_name }}"
          echo "github.sha ${{ github.sha }}"
          echo "GitHub - ${{ github }}"

  publish-test-reports:
    name: Publish test reports to gh-pages
    needs: unit
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: IndranilKhedkar/github-actions/.github/workflows/publish-gh-pages.yml@test-github-workflow
    with:
      artifacts: '{\"Coverage report\": \"unit-tests-coverage\", \"Test results\": \"unit-tests\"}'
      comment-title: 'Unit test reports'
